---
abstract: 'Params::Validate-like parameter validation using Type::Tiny type constraints and coercions'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Type::Params
name: Type-Params
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Eval::Closure: 0
  Type::Tiny: 0.003_04
  perl: 5.8.1
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-Params
  homepage: https://metacpan.org/release/Type-Params
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-type-params
version: 0.000_05
